version: "3.3"

services:
  app:
    image: "image-name"
    build: .
    ports:
      - "2023:3000"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./next-sitemap.config.js:/app/next-sitemap.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./next.config.js:/app/next.config.js

  # nginx:
  #   image: "nginx:1.25.0-alpine"
  #   ports:
  #     - "3001:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
